POST {{$dotenv host}}/auth/register
Content-Type: application/json

{
  "name": "Admin",
  "email": "admin@babelcoder.com",
  "password": "password"
}

###

POST {{$dotenv host}}/auth/login
Content-Type: application/json

{
  "email": "admin@babelcoder.com",
  "password": "password"
}

###

POST {{$dotenv host}}/auth/refresh-token
Content-Type: application/json

{
  "refreshToken": "{{$dotenv refreshToken}}"
}

###

GET {{$dotenv host}}/auth/profile
Authorization: Bearer {{$dotenv accessToken}}

###

PATCH {{$dotenv host}}/auth/profile
Authorization: Bearer {{$dotenv accessToken}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name"

Admin
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="address[houseNumber]"

111/11
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="address[village]"

Xx
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="address[road]"

Petchaburi
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="address[district]"

Ratchatawee
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="address[province]"

Mukkasun
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="address[postalCode]"

10250
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="avatar.png"
Content-Type: image/png

< ./http/data/avatar.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

DELETE {{$dotenv host}}/auth/logout
Authorization: Bearer {{$dotenv accessToken}}

###

POST {{$dotenv host}}/products
Authorization: Bearer {{$dotenv accessToken}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name"

My Product
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="price"

2000
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="desc"

Product 1 Desc
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="categoryIds[]"

1
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="product.png"
Content-Type: image/png

< ./http/data/product.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

PATCH  {{$dotenv host}}/products/1
Authorization: Bearer {{$dotenv accessToken}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name"

Product 1
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="desc"

Product 1 Desc
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="categoryIds[]"

1
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="product.png"
Content-Type: image/png

< ./http/data/product.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

GET {{$dotenv host}}/products?page=2

###

GET {{$dotenv host}}/products/1

###

DELETE  {{$dotenv host}}/products/1

###

POST {{$dotenv host}}/categories
Content-Type: application/json

{
  "name": "Category 1",
  "desc": "Category 1 Desc"
}

###

PATCH  {{$dotenv host}}/categories/1
Content-Type: application/json

{
  "name": "Category-1",
  "desc": "Category 1 Desc"
}

###

GET {{$dotenv host}}/categories

###

GET {{$dotenv host}}/categories/1

###

DELETE  {{$dotenv host}}/categories/1

###